#!/bin/bash
#
#
#	On a windows system, this wrapper allows you to call BRAHMS with
#	the loader path PATH conveniently set. There are three possible
#	outcomes:
#
#		1) Lockfile deleted, error level 0 (success).
#		2) Lockfile deleted, error level 1 (exception).
#		3) Lockfile not deleted (abort).
#
#	Usage:
#
#		brahms ...
#
#	The first form will pass all arguments straight through to the
#	execute function, after setting the loader path appropriately.
#
#	From Matlab:
#
#		brahms matlab ...
#
#	Called as above, the wrapper will exit the shell on failure,
#	which forces Matlab to acknowledge the failure return code, rather
#	than just setting ERRORLEVEL, which Matlab will ignore.
#
#
#
#
#________________________________________________________________
#
#	This file is part of BRAHMS
#	Copyright (C) 2007 Ben Mitchinson
#	URL: http:sourceforge.net/projects/abrg-brahms
#
#	This program is free software; you can redistribute it and/or
#	modify it under the terms of the GNU General Public License
#	as published by the Free Software Foundation; either version 2
#	of the License, or (at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program; if not, write to the Free Software
#	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#________________________________________________________________
#
#	Subversion Repository Information (automatically updated on commit)
#
#	$Id:: brahms 2276 2009-11-01 17:30:15Z benjmitch           $
#	$Rev:: 2276                                                $
#	$Author:: benjmitch                                        $
#	$Date:: 2009-11-01 17:30:15 +0000 (Sun, 01 Nov 2009)       $
#________________________________________________________________
#


# script revised at R2134 - see brahms.bat (windows shell
# script) for more info.


# set path (only required with bash on Windows?)
#BINPATH=`echo $0 | sed s/\\\\\(.*\\\\\)\\\/.*/\\\1/`
#export PATH=$PATH:$BINPATH
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$BINPATH

# call BRAHMS executable
brahms-execute "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8"


# I think this will just pass on the return code to the
# return code of this script - if not, on your platform,
# you might use something like the following instead...
#
# (this was designed using bash, syntax for other shells
# may be different)
#
# ERR=$?
# if [ "$ERR" -ne "0" ];
# then
# 	exit $ERR
# fi



